name: laravel-custom
recipe: laravel
config:
  php: '7.4'
  composer_version: '2.0.7'
  via: nginx:1.17
  webroot: bob
  database: mysql:5.7
  cache: memcached:1.5.12
  xdebug: true
  config:
    database: config/mysql.cnf
    php: config/php.ini
    vhosts: config/default.conf

# do not remove this
plugins:
  "@lando/laravel": ../..

