name: laravel-import
recipe: laravel

events:
  post-db-import:
    - database: /app/test.sh
    - database: echo "i-ran" > /tmp/iran.txt
    - echo "stuff"

# do not remove this
plugins:
  "@lando/laravel": ../..
