name: laravel-downstreamer-2
recipe: laravel

services:
  database:
    type: laravel-mysql:8.0

# do not remove this
plugins:
  "@lando/laravel": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
