name: Add to Contrib Project

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue/PR to GitHub Project
        if: github.event.label.name == 'flag'
        uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/lando/projects/7
          github-token: ${{ secrets.SHADOW_COUNCIL_ESCALATOR }}
          labeled: flag
